version: '3.8'

services:
  backend:
    build: .
    container_name: shopverse_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/shopverse
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=shopverse_pass
    depends_on:
      - db
    networks:
      - shopverse_net

  frontend:
    build:
      context: ./Frontend
    container_name: shopverse_frontend
    ports:
      - "80:80"
    networks:
      - shopverse_net

  db:
    image: mysql:8.0
    container_name: shopverse_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shopverse_pass
      MYSQL_DATABASE: shopverse
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shopverse_net

networks:
  shopverse_net:

volumes:
  db_data: